Changed Queues to BlockingQueues and removed wait() and notifyAll() which were causing exceptions. Now getting a really weird exception - NoClassDefFoundError for StringConcatFactory while using + operator to build a string? Never seen that before.